### ISSUE TITLE
CSS Property expecting multiple extra parameters

### ISSUE THREAD

**Issue by Vips19** [jamesshore/quixote#64]
@jamesshore 
![Screenshot (600)](https://user-images.githubusercontent.com/29044523/133761393-73154ca3-776e-4a1c-b926-0d9e2dc9ddcc.png)

CSS property 'text-decoration: none' is expecting 'none solid rgb(255, 255, 255)' .

Is there any style guide for css properties?

**Comment by jamesshore** [comment]
Because Quixote doesn't yet have a descriptor for underlines, I presume you were using `getRawStyle()`. That API returns the exact text provided by the browser (with minor exceptions—see [the documentation](https://github.com/jamesshore/quixote/blob/release/docs/QElement.md#elementgetrawstyle)). So to make this test pass, you'll need to use the `none solid rgb(255, 255, 255)` rather than `none`. However, it's still appropriate to use `none` in your production code.

I'm not aware of an official style guide for CSS properties, but [MDN's documentation](https://developer.mozilla.org/en-US/docs/Web/CSS) is excellent.
